const constants = {
  ERROR_INVALID_REQUEST: "INVALID_REQUEST",
  ERROR_INVALID_TOKEN: "INVALID_TOKEN",
  ERROR_INVALID_ACCEPT: "INVALID_ACCEPT",
  ERROR_FORBIDDEN: "FORBIDDEN",
  ERROR_GENERIC: "GENERIC_ERROR",
  ERROR_RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  HTTP_OK: 200,
  HTTP_CREATED: 201,
  HTTP_NO_CONTENT: 204,
  HTTP_BAD_REQUEST: 400,
  HTTP_UNAUTHORIZED: 401,
  HTTP_FORBIDDEN: 403,
  HTTP_NOT_FOUND: 404,
  HTTP_NOT_ACCEPTABLE: 406,
  HTTP_BAD_FIELDS: 412,
  HTTP_SERVER_ERROR: 500,

  // header
  CONTENT_TYPE: "application/json",

  // test JWT
  TEST_JWT:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9FSkRNalJCUVRrelFrWTJNVU15UlRoRFJqVXdPVEV3TkRVNFFUSTFOelUxUWtRMVJVVXpPUSJ9.eyJpc3MiOiJodHRwczovL21vY2stYmFua2luZy1hcGkuYXV0aDAuY29tLyIsInN1YiI6ImdNRkdPbXUwMTU4UDlucFRVTXNhWG9kOEhQM04zRnFKQGNsaWVudHMiLCJhdWQiOiJodHRwczovL2FwaS5tb2NrYmFua2luZy5jb20iLCJpYXQiOjE1NzQ5MTc5NzEsImV4cCI6MTU3NTAwNDM3MSwiYXpwIjoiZ01GR09tdTAxNThQOW5wVFVNc2FYb2Q4SFAzTjNGcUoiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.VajgJ-rFfQvTjZeMOMsnm2pENjtgymcTPn5yXpvmL1C1Fag3afwQ0fdnHRoYI4XW6POxNRMpY0y-xG-5vwWOK9wr8wjweo0RxPbE0BDPAFkFrwYH70m0SsVTAf63kISa71FJ6ktRtAeGJrJWt8GGpyaRr5wg54zKqeRgrBJI6V-khKSUlcy66m6xTtb_-Rn-HsvTvD-bLqlSvevJPEGPSKUcM1cHkWH_-eosaZzSv9OA6ksblgEvUOZeP8nrWR_KzGN7LaF-QtvUCwheRaEdmGvhbDunVEx3XuXgt_URbZcAqrMnHXsrVh_H2_Yn7_vrxgXvdQkBZHRHEH6uywyvDw"
};

export default constants;
